In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, BatchNormalization, Activation, Dropout

#loading the MNIST dataset
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()
#analyzing the image
print(x_train)

#for checking the size
print(x_train.shape)

print(y_train)

#for checking the size of the y_train
print(y_train.shape)

print(x_test)
#for checking the size of the x_test
print(x_test.shape)

print(y_test)
#for checking the size of
print(y_test.shape)
#preprocesing the data
x_train =x_train.reshape(-1,784).astype("float32")/255.0
x_test = x_test.reshape(-1,784).astype("float32")/255.0
#ONE HOT ENCODING
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)
#developing the model
ann = tf.keras.models.Sequential()

for _ in range(9):
    ann.add(tf.keras.layers.Dense(units=6, use_bias=False))
    #Batch normalization is added because it will normalize the output of each layer means higher outputs get normalized and If it is not normalized then each layer output is random and difficult to train the next layer
    ann.add(tf.keras.layers.BatchNormalization())
    ann.add(tf.keras.layers.Activation('relu'))
    #drop out means it will randomly drops some neurons so that it will start learning instead of memorizing as here we are passing 0.1 then it means 10% of neurons are getting skipped
    ann.add(tf.keras.layers.Dropout(0.1))

#adding output layer
#here if our model has the output based in 10 columns that why we need to add the 10 neurons inside the output layer
#means if we have to choose the only one output then use softmax and if we had to choose the multiple outputs then use sigmoid
ann.add(tf.keras.layers.Dense(units=10 , activation='softmax'))
ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
# You might need to adjust batch_size and epochs based on your needs
ann.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_test, y_test))


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
(60000, 28, 28)
[5 0 4 ... 5 6 8]
(60000,)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0

In [3]:
#training the model with fixed learning rate
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

#applying the step decay type of learning rate
def step_decay()

#developing the model
ann = tf.keras.models.Sequential()

for _ in range(9):
    ann.add(tf.keras.layers.Dense(units=6, use_bias=False))
    #Batch normalization is added because it will normalize the output of each layer means higher outputs get normalized and If it is not normalized then each layer output is random and difficult to train the next layer
    ann.add(tf.keras.layers.BatchNormalization())
    ann.add(tf.keras.layers.Activation('relu'))
    #drop out means it will randomly drops some neurons so that it will start learning instead of memorizing as here we are passing 0.1 then it means 10% of neurons are getting skipped
    ann.add(tf.keras.layers.Dropout(0.1))

#adding output layer
#here if our model has the output based in 10 columns that why we need to add the 10 neurons inside the output layer
#means if we have to choose the only one output then use softmax and if we had to choose the multiple outputs then use sigmoid
ann.add(tf.keras.layers.Dense(units=10 , activation='softmax'))
ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
# You might need to adjust batch_size and epochs based on your needs
ann.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_test, y_test))


Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - accuracy: 0.1678 - loss: 2.2165 - val_accuracy: 0.3995 - val_loss: 1.6081
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.2972 - loss: 1.8503 - val_accuracy: 0.4162 - val_loss: 1.4479
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.3178 - loss: 1.7460 - val_accuracy: 0.4192 - val_loss: 1.3098
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.3318 - loss: 1.6710 - val_accuracy: 0.4295 - val_loss: 1.3059
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.3323 - loss: 1.6372 - val_accuracy: 0.4434 - val_loss: 1.2813
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.3423 - loss: 1.6183 - val_accuracy: 0.4522 - val_loss: 1.2719
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.3459 - loss: 1.6084 - val_accuracy: 0.4553 - val_loss: 1.2641
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.3497 - loss: 1.5931 -