In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, BatchNormalization, Activation, Dropout

#loading the MNIST dataset
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()

In [2]:
#analyzing the image
print(x_train)

#for checking the size
print(x_train.shape)

print(y_train)

#for checking the size of the y_train
print(y_train.shape)

print(x_test)
#for checking the size of the x_test
print(x_test.shape)

print(y_test)
#for checking the size of
print(y_test.shape)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
(60000, 28, 28)
[5 0 4 ... 5 6 8]
(60000,)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 

In [3]:
#preprocesing the data
x_train =x_train.reshape(-1,784).astype("float32")/255.0
x_test = x_test.reshape(-1,784).astype("float32")/255.0

In [4]:
#ONE HOT ENCODING
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)

In [15]:
#developing the model
ann = tf.keras.models.Sequential()

for _ in range(9):
    ann.add(tf.keras.layers.Dense(units=6, use_bias=False))
    #Batch normalization is added because it will normalize the output of each layer means higher outputs get normalized and If it is not normalized then each layer output is random and difficult to train the next layer
    ann.add(tf.keras.layers.BatchNormalization())
    ann.add(tf.keras.layers.Activation('relu'))
    #drop out means it will randomly drops some neurons so that it will start learning instead of memorizing as here we are passing 0.1 then it means 10% of neurons are getting skipped
    ann.add(tf.keras.layers.Dropout(0.1))

#adding output layer
#here if our model has the output based in 10 columns that why we need to add the 10 neurons inside the output layer
#means if we have to choose the only one output then use softmax and if we had to choose the multiple outputs then use sigmoid
ann.add(tf.keras.layers.Dense(units=10 , activation='softmax'))

In [16]:
#using the optimizer to run the code
ann.compile(optimizer='adam', loss='mean_squared_error',metrics=['accuracy'])

#to train the model
history = ann.fit(x_train, y_train, batch_size = 32, epochs = 20 , validation_data=(x_test, y_test))

Epoch 1/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - accuracy: 0.1615 - loss: 0.0883 - val_accuracy: 0.3014 - val_loss: 0.0774
Epoch 2/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.2520 - loss: 0.0806 - val_accuracy: 0.3007 - val_loss: 0.0742
Epoch 3/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.2655 - loss: 0.0785 - val_accuracy: 0.3049 - val_loss: 0.0732
Epoch 4/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.2690 - loss: 0.0773 - val_accuracy: 0.3064 - val_loss: 0.0727
Epoch 5/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.2791 - loss: 0.0767 - val_accuracy: 0.3018 - val_loss: 0.0730
Epoch 6/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.2723 - loss: 0.0767 - val_accuracy: 0.3062 - val_loss: 0.0724
Epoch 7/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.2900 - loss: 0.0758 - val_accuracy: 0.3731 - val_loss: 0.0705
Epoch 8/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.3171 - loss: 0.

In [17]:
final_train_acc = history.history['accuracy'][-1]
final_val_acc = history.history['val_accuracy'][-1]

print(f"Final Training Accuracy: {final_train_acc:.4f}")
print(f"Final Validation Accuracy: {final_val_acc:.4f}")


Final Training Accuracy: 0.3296
Final Validation Accuracy: 0.3831


In [18]:
test_loss, test_accuracy = ann.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Test Accuracy: 0.3831000030040741
